forum/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='forum-index'),
    url(r'^(?P<forum_id>\d+)(?:-(?P<slug>[\w\d-]+))?/$', views.forum, name='forum-detail'),
    url(r'^(?P<slug>[\w\d-]+)/$', views.section, name='section-detail'),
    url(r'^closeforum/(\d+)/$', views.closeforum, name='forum-close'),
    url(r'^topic/(?P<topic_id>\d+)(?:-(?P<slug>[\w\d-]+))?/$', views.topic, name='topic-detail'),
    url(r'^pintopic/(\d+)/$', views.pintopic, name='topic-pin'),
    url(r'^closetopic/(\d+)/$', views.closetopic, name='topic-close'),
    url(r'^reply/(\d+)/$', views.post_reply, name='reply'),
    url(r'^editreply/(\d+)/$', views.post_reply_edit, name='reply-edit'),
    url(r'^removereply/(\d+)/$', views.post_reply_remove, name='reply-remove'),
    url(r'newtopic/(\d+)/$', views.new_topic, name='new-topic'),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.template.defaultfilters import slugify

class Section(models.Model):
    title = models.CharField(max_length=60)
    slug = models.SlugField(blank=True, null=True)
    description = models.TextField(blank=True, default='')
    priority = models.IntegerField(default=1)

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Section, self).save(*args, **kwargs)

    def forums(self):
        return Forum.objects.filter(section=self)

class Forum(models.Model):
    title = models.CharField(max_length=60)
    slug = models.SlugField(blank=True, null=True)
    description = models.TextField(blank=True, default='')
    updated = models.DateTimeField()
    created = models.DateTimeField(editable=False)
    creator = models.ForeignKey(User, blank=True, null=True)
    closed = models.BooleanField(blank=True, default=False)
    section = models.ForeignKey(Section)

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.updated = timezone.now()

        self.slug = slugify(self.title)

        return super(Forum, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

    def num_topics(self):
        return len(self.topic_set.all())

    def num_posts(self):
        return sum([t.num_posts() for t in self.topic_set.all()])

    def last_post(self):
        if self.topic_set.count():
            last = None
            for t in self.topic_set.all():
                l = t.last_post()
                if l:
                    if not last: last = l
                    elif l.created > last.created: last = l
            return last

    class Meta(object):
        permissions = (
            ("can_lock_forum", "Can change forum lock status"),
            ("can_post_lock_forum", "Can post in locked forums"),
        )

class Topic(models.Model):
    title = models.CharField(max_length=60)
    slug = models.SlugField(blank=True, null=True)
    description = models.TextField(max_length=10000, blank=True, null=True)
    forum = models.ForeignKey(Forum)
    created = models.DateTimeField(editable=False)
    creator = models.ForeignKey(User, blank=True, null=True)
    updated = models.DateTimeField()
    closed = models.BooleanField(blank=True, default=False)
    pinned = models.BooleanField(blank=True, default=False)
    views = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.updated = timezone.now()

        self.slug = slugify(self.title)

        return super(Topic, self).save(*args, **kwargs)

    def num_posts(self):
        return self.post_set.count()

    def num_replies(self):
        return self.post_set.count()

    def last_post(self):
        if self.post_set.count():
            return self.post_set.order_by("-created")[0]

    def __unicode__(self):
        return unicode(self.creator) + " - " + self.title

    class Meta(object):
        permissions = (
            ("can_close_topic", "Can change topic closed status"),
            ("can_pin_topic", "Can change topic pinned status"),
        )

class Post(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(editable=False)
    creator = models.ForeignKey(User, blank=True, null=True)
    updated = models.DateTimeField()
    topic = models.ForeignKey(Topic)
    body = models.TextField(max_length=10000)
    user_ip = models.GenericIPAddressField(blank=True, null=True)
    removed = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.updated = timezone.now()
        return super(Post, self).save(*args, **kwargs)

    def __unicode__(self):
        return u"%s - %s - %s" % (self.creator, self.topic, self.title)

    def short(self):
        return u"%s - %s\n%s" % (self.creator, self.title, self.created.strftime("%b %d, %H:%M"))

    def is_modified(self):
        if self.updated.replace(microsecond=0) > self.created.replace(microsecond=0):
            return True
        return False

    short.allow_tags = True

    class Meta(object):
        permissions = (
            ("can_remove_post", "Can remove a post"),
            ("can_see_poster_ip", "Can see posters IP address"),
        )


class ProfaneWord(models.Model):
    word = models.CharField(max_length=60)

    def __unicode__(self):
        return self.word

forum/templates/forum/forum.html
{% extends "personal/header.html" %}
{% block sitename %}<a href="/forum">LunaSquee Forums</a>{% endblock %}
{%block title%}LunaSquee Forums - {{section.title}} >> {{forum.title}}{%endblock%}
{% block content %}
<!-- Forum Navigator -->
<div class="forumnavigator">
    <a href="/forum" class="instance" style="z-index: 3;">Forum index</a>
    <a href="{% url 'section-detail' section.slug %}" class="instance" style="z-index: 2;">{{section.title}}</a>
    <a href="{% url 'forum-detail' forum.pk forum.slug %}" class="instance" style="z-index: 1;">{{forum.title}}</a>
</div><br>
<!-- Forum Title -->
<span class="forumtitle"><span>Forum</span>{{forum.title}}</span>
<span class="forumdescription">{{forum.description}}</span>
<!-- Threads  -->
{% if not forum.closed or perms.forum.can_post_lock_forum %}
<a id="new_topic" class="button" href="{% url 'new-topic' pk %}">Start New Topic</a>
{% else %}
<div class="errorbox">This forum is closed for new topics.</div>
{% endif %}
<br />
<br />
<!-- Next/Prev page links  -->
{% if topics.object_list and topics.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links">
        {% if topics.has_previous %}
            <a href= "?page={{ topics.previous_page_number }}"><i class="fa fa-angle-double-left"></i>&nbsp;Previous</a>
        {% endif %}

        <span class="current">
            &nbsp;Page {{ topics.number }} of {{ topics.paginator.num_pages }}
        </span>

        {% if topics.has_next %}
            <a href="?page={{ topics.next_page_number }}">Next&nbsp;<i class="fa fa-angle-double-right"></i></a>
        {% endif %}
    </span>
</div>
{% endif %}
<div id="list">
<table border="0" cellpadding="4" width="100%">
    <tr>
        <th class="indic">&nbsp;</th>
        <th>Topics</th>
        <th class="count_part">Replies</th>
        <th class="count_part">Views</th>
        <th>Last post</th>
        {% if perms.forum.change_forum %}
        <th>Actions</th>
        {% endif %}
    </tr>

    {% for topic in topics.object_list %}
    <tr>
        <td class="indic{% if forloop.last %} last{% endif %}">&nbsp;</td>
        <td {% if forloop.last %}class="last"{% endif %}>
        <div class="title">{%if topic.closed%}<i class="fa fa-ban fa-fw" title="Topic is closed for new replies"></i>{%endif%}{%if topic.pinned%}<i class="fa fa-thumb-tack fa-fw" title="Pinned topic"></i>{%endif%}
        <a href="{% url 'topic-detail' topic.pk topic.slug %}">{{ topic.title }}</a><br><span class="createdby">
            Started by <a href="{% url 'view_other_profile' topic.creator.username %}">{{topic.creator.profile.displayable_name}}</a> on {{topic.created|date:"l, N d Y, H:i"}}</span></div></td>
        <td class="count_part{% if forloop.last %} last{% endif %}">{{ topic.num_replies }}</td>
        <td class="count_part{% if forloop.last %} last{% endif %}">{{ topic.views }}</td>
        <td {% if forloop.last %}class="last"{% endif %}>
        {%if topic.last_post%}
            <a href="{% url 'topic-detail' topic.last_post.topic.pk topic.last_post.topic.slug %}?find_post={{topic.last_post.pk}}">{{ topic.last_post.title }}</a><br><span class="createdby">By <a href="{%url 'view_other_profile' topic.last_post.creator%}">{{topic.last_post.creator.profile.displayable_name}}</a> on {{topic.last_post.created|date:"l, N d Y, H:i"}}</span>
        {%else%}
            <small><i>Nobody has posted here yet!</i></small>
        {%endif%}
        </td>
        {% if perms.forum.change_topic %}
            <td class="actions{% if forloop.last %} last{% endif %}">
            {% if perms.forum.can_pin_topic %}
            <a href="{% url 'topic-pin' topic.pk %}" title="Pin topic"><i class="fa fa-thumb-tack fa-fw"></i></a>
            {% endif %}
            {% if perms.forum.can_close_topic %}
            <a href="{% url 'topic-close' topic.pk %}" title="Close topic"><i class="fa fa-ban fa-fw"></i></a>
            {% endif %}
            </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
</div>

<!-- Next/Prev page links  -->
{% if topics.object_list and topics.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links">
        {% if topics.has_previous %}
            <a href= "?page={{ topics.previous_page_number }}"><i class="fa fa-angle-double-left"></i>&nbsp;Previous</a>
        {% endif %}

        <span class="current">
            &nbsp;Page {{ topics.number }} of {{ topics.paginator.num_pages }}
        </span>

        {% if topics.has_next %}
            <a href="?page={{ topics.next_page_number }}">Next&nbsp;<i class="fa fa-angle-double-right"></i></a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}

forum/templates/forum/list.html
{% extends "personal/header.html" %}
{% block sitename %}<a href="/forum">LunaSquee Forums</a>{% endblock %}
{%block title%}LunaSquee Forums{%endblock%}
{% block content %}
<!-- Forums  -->
<div class="forumnavigator">
    <a href="/forum" class="instance" style="z-index: 4;">Forum index</a>
</div><br>
{% for section in sections %}
<span class="sectiontitle">{{section.title}}</span>
<span class="forumdescription">{{section.description|safe}}</span>
<div id="list">
    <table border="0" cellpadding="4" width="100%">
        <tr>
            <th class="indic">&nbsp;</th>
            <th>Forum</th>
            <th class="count_part">Topics</th>
            <th class="count_part">Posts</th>
            <th>Last post</th>
            {% if "forum.change_forum" in perms %}
            <th>Actions</th>
            {% endif %}
        </tr>
        {% for forum in section.forums %}
            <tr>
                <td class="indic{% if forloop.last %} last{% endif %}">
                    <span>
                    {% if forum.closed %}
                        <i class="fa fa-lock" title="This forum is locked"></i>
                    {% else %}
                        <i class="fa fa-user" title="Registered users can post here"></i>
                    {% endif %}
                    </span>
                </td>
                <td {% if forloop.last %}class="last"{% endif %}>
                    <div class="title"> <a href="{% url 'forum-detail' forum.pk forum.slug %}">{{ forum.title }}</a><br>
                    <span>{{forum.description}}</span></div>
                </td>
                <td class="count_part" {% if forloop.last %}class="last"{% endif %}>{{ forum.num_topics }}</td>
                <td class="count_part" {% if forloop.last %}class="last"{% endif %}>{{ forum.num_posts }}</td>
                <td {% if forloop.last %}class="last"{% endif %}>
                {%if forum.last_post %}
                    <a href="{% url 'topic-detail' forum.last_post.topic.pk forum.last_post.topic.slug %}?find_post={{forum.last_post.pk}}">{{ forum.last_post.title }}</a><br><span class="createdby">By <a href="{%url 'view_other_profile' forum.last_post.creator%}">{{forum.last_post.creator.profile.displayable_name}}</a> on {{forum.last_post.created|date:"l, N d Y, H:i"}}</span>
                {%else%}
                    <small><i>Nobody has posted here yet!</i></small>
                {%endif%}
                </td>
                {% if "forum.change_forum" in perms %}
                    <td class="actions{% if forloop.last %} last{% endif %}">
                        {% if "forum.can_lock_forum" in perms %}
                            <a href="{% url 'forum-close' forum.pk %}" title="Lock forum"><i class="fa fa-lock fa-fw"></i></a>
                        {% endif %}
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
</div>
{% endfor %}
{% endblock %}

forum/templates/forum/new-topic.html
{% extends "personal/header.html" %}
{% block sitename %}<a href="/forum">LunaSquee Forums</a>{% endblock %}
{% block title %}LunaSquee Forums - New topic on {{forum.section.title}}{% endblock %}
{% block content %}
<!-- Forum Navigator -->
<div class="forumnavigator">
    <a href="/forum" class="instance" style="z-index: 3;">Forum index</a>
    <a href="{% url 'section-detail' forum.section.slug %}" class="instance" style="z-index: 2;">{{forum.section.title}}</a>
    <a href="{% url 'forum-detail' forum.pk forum.slug %}" class="instance" style="z-index: 1;">{{forum.title}}</a>
    <span class="instance">New topic</span>
</div><br>
<!-- New Topic Form -->
<span class="topictitle">Create a new topic in {{forum.title}}</span>
<form action="{% url 'new-topic' forum.id %}" method="POST">
    {% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
<script> CKEDITOR.replace( 'id_description' ); </script>
{% endblock %}

forum/templates/forum/reply.html
{% extends "personal/header.html" %}
{% block sitename %}<a href="/forum">LunaSquee Forums</a>{% endblock %}
{%block title%}LunaSquee Forums - Replying to topic {{topic.title}}{%endblock%}
{% block content %}
<!-- Forum Navigator -->
<div class="forumnavigator">
    <a href="/forum" class="instance" style="z-index: 4;">Forum index</a>
    <a href="{% url 'section-detail' forum.section.slug %}" class="instance" style="z-index: 3;">{{forum.section.title}}</a>
    <a href="{% url 'forum-detail' forum.pk forum.slug %}" class="instance" style="z-index: 2;">{{forum.title}}</a>
    <a href="{% url 'topic-detail' topic.pk topic.slug %}" class="instance" style="z-index: 1;">{{topic.title}}</a>
    {% if not editing %}
    <span class="instance">New reply</span>
    {% else %}
    <span class="instance">Edit reply</span>
    {% endif %}
</div><br>
<!-- Reply Form -->
{% if not editing %}
<i><small>Replying to</small></i>
{% else %}
<i><small>Editing reply to</small></i>
{% endif %}
<span class="topictitle"><span>Topic</span>{{topic.title}}</span>
<form action method="POST">
    {% csrf_token %} 
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    <a href="{% url 'topic-detail' topic.pk %}" class="button replybtn">Back to topic</a>
</form>
<script> CKEDITOR.replace( 'id_body' ); </script>
{% endblock %}

forum/templates/forum/section.html
{% extends "personal/header.html" %}
{% block sitename %}<a href="/forum">LunaSquee Forums</a>{% endblock %}
{%block title%}LunaSquee Forums - {{section.title}}{%endblock%}
{% block content %}
<!-- Forums  -->
<div class="forumnavigator">
    <a href="/forum" class="instance" style="z-index: 4;">Forum index</a>
    <a href="{% url 'section-detail' section.slug %}" class="instance" style="z-index: 3;">{{section.title}}</a>
</div><br>
<span class="sectiontitle">{{section.title}}</span>
<span class="forumdescription">{{section.description|safe}}</span>
<div id="list">
    <table border="0" cellpadding="4" width="100%">
        <tr>
            <th class="indic">&nbsp;</th>
            <th>Forum</th>
            <th class="count_part">Topics</th>
            <th class="count_part">Posts</th>
            <th>Last post</th>
            {% if "forum.change_forum" in perms %}
            <th>Actions</th>
            {% endif %}
        </tr>
        {% for forum in forums %}
            <tr>
                <td class="indic{% if forloop.last %} last{% endif %}">
                    <span>
                    {% if forum.closed %}
                        <i class="fa fa-lock" title="This forum is locked"></i>
                    {% else %}
                        <i class="fa fa-user" title="Registered users can post here"></i>
                    {% endif %}
                    </span>
                </td>
                <td {% if forloop.last %}class="last"{% endif %}>
                    <div class="title"> <a href="{% url 'forum-detail' forum.pk forum.slug %}">{{ forum.title }}</a><br>
                    <span>{{forum.description}}</span></div>
                </td>
                <td class="count_part" {% if forloop.last %}class="last"{% endif %}>{{ forum.num_topics }}</td>
                <td class="count_part" {% if forloop.last %}class="last"{% endif %}>{{ forum.num_posts }}</td>
                <td {% if forloop.last %}class="last"{% endif %}>
                {%if forum.last_post %}
                    <a href="{% url 'topic-detail' forum.last_post.topic.pk forum.last_post.topic.slug %}?find_post={{forum.last_post.pk}}">{{ forum.last_post.title }}</a><br><span class="createdby">By <a href="{%url 'view_other_profile' forum.last_post.creator%}">{{forum.last_post.creator.profile.displayable_name}}</a> on {{forum.last_post.created|date:"l, N d Y, H:i"}}</span>
                {%else%}
                    <small><i>Nobody has posted here yet!</i></small>
                {%endif%}
                </td>
                {% if "forum.change_forum" in perms %}
                    <td class="actions{% if forloop.last %} last{% endif %}">
                        {% if "forum.can_lock_forum" in perms %}
                            <a href="{% url 'forum-close' forum.pk %}" title="Lock forum"><i class="fa fa-lock fa-fw"></i></a>
                        {% endif %}
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

forum/templates/forum/topic.html
{% extends "personal/header.html" %}
{% block sitename %}<a href="/forum">LunaSquee Forums</a>{% endblock %}
{% block title %}LunaSquee Forums - Viewing topic {{topic.title}} by {{topic.creator.profile.displayable_name}}{% endblock %}
{% block content %}
<!-- Forum Navigator -->
<div class="forumnavigator">
    <a href="/forum" class="instance" style="z-index: 4;">Forum index</a>
    <a href="{% url 'section-detail' section.slug %}" class="instance" style="z-index: 3;">{{section.title}}</a>
    <a href="{% url 'forum-detail' forum.pk forum.slug %}" class="instance" style="z-index: 2;">{{forum.title}}</a>
    <a href="{% url 'topic-detail' topic.pk topic.slug %}" class="instance" style="z-index: 1;">{{topic.title}}</a>
</div><br>
<!-- Posts  -->
<span class="topictitle"><span>Topic</span>{{ topic.title }}</span>
<span class="topicdescription"><a href="{% url 'view_other_profile' topic.creator.username %}" target="_blank">{{topic.creator.profile.displayable_name}}</a> started this topic on {{ topic.created|date:"l, N d Y, H:i" }}</span>
<!-- Next/Prev page links  -->
{% if posts.object_list and posts.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href= "?page={{ posts.previous_page_number }}"><i class="fa fa-angle-double-left"></i>&nbsp;Previous</a>
        {% endif %}

        <span class="current">
            &nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">Next&nbsp;<i class="fa fa-angle-double-right"></i></a>
        {% endif %}
    </span>
</div>
{% endif %}
<div class="boxheader">
<span class="replycount">This topic has {{post_count}} replies</span>
{% if not topic.closed %}
    {% if not forum.closed or perms.forum.can_post_lock_forum %}
        <a class="button replybtn" href="{% url 'reply' pk %}">Reply</a>
    {%endif%}
{%endif%}
</div>
<div id="postlist">
    {% for post in posts.object_list %}
    <div id="post-{{post.pk}}">
        <div class="p_username">
            {% if post.creator.profile.online %}
            <span class="statuscirc online" title="Last seen: {{ post.creator.profile.last_seen|timesince }} ago">&nbsp;</span>
            {% else %}
            <span class="statuscirc offline" title="Last seen: {% if post.creator.profile.last_seen %}{{ post.creator.profile.last_seen|timesince }} {% else %}A long time {% endif %}ago">&nbsp;</span>
            {% endif %}
            <a href="{% url 'view_other_profile' post.creator.username %}">{{ post.creator.profile.displayable_name}}</a>
            {% load postnumber %}
            <a href="#post-{{post.pk}}" class="postid">#{{ forloop.counter|postnumber:posts.number }}</a>
            
            {% if perms.forum.can_see_poster_ip %}<a href="#{{ post.user_ip }}" class="ipaddr"><i class="fa fa-globe"></i>&nbsp;{{ post.user_ip }}</a>{% endif %}
        </div>
        <div class="post">
            <div class="poster">
                <img class="avatar" src="{{ post.creator.profile.get_avatar }}">
                <div class="badges">
                    {% for badge in post.creator.profile.badges %}
                    <div class="badge b-{{badge.title}}">
                        {{badge.display}}
                    </div>
                    {% endfor %}
                </div>
                <span class="reputation{%if topic.creator.profile.reputation < 0%} negative{%endif%}"><span>{{topic.creator.profile.reputation}}</span> Reputation</span>
                <span class="post_count newparam">Posts: <span>{{post.creator.profile.get_post_count}}</span></span>
                <span class="topic_count newparam">Topics: <span>{{post.creator.profile.get_topic_count}}</span></span>
            </div>
            <div class="container">
            {% if post.removed %}
                <span class="removed-post">This post has been removed by an administator.</span>
            {% else %}
                {{ post.body|safe }}
            {% endif %}
            </div>
            <div class="subarea">
                {% if post.creator == user and not post.closed %}
                    {% if not forum.closed or perms.forum.can_post_lock_forum %}
                        <a href="{% url 'reply-edit' post.pk %}" class="button">Edit</a>
                    {% endif %}
                {% endif %}
                {% if perms.forum.can_remove_post %}
                    <a href="{% url 'reply-remove' post.pk %}" class="button">
                        {% if post.removed %}Restore{% else %}Remove{% endif %}
                    </a>
                {% endif %}
                <span class="date">{{ post.created|date:"l, N d Y, H:i" }}</span>
                {% if post.is_modified %}
                <span class="date updated">Updated {{ post.updated|date:"l, N d Y, H:i" }}</span>
                {% endif %}
            </div>
            <span class="vertical_divider"></span>
        </div>
    </div>
    {% endfor %}
</div>
<div class="boxfooter">
&nbsp;
{% if not topic.closed %}
    {% if not forum.closed or perms.forum.can_post_lock_forum %}
        <a class="button replybtn" href="{% url 'reply' pk %}">Reply</a>
    {%endif%}
{%endif%}
</div>

<!-- Next/Prev page links  -->
{% if posts.object_list and posts.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href= "?page={{ posts.previous_page_number }}"><i class="fa fa-angle-double-left"></i>&nbsp;Previous</a>
        {% endif %}

        <span class="current">
            &nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">Next&nbsp;<i class="fa fa-angle-double-right"></i></a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}